# Generated by Django 3.2 on 2022-01-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='ntn_type',
            new_name='_type',
        ),
    ]
