# Generated by Django 3.2 on 2022-01-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_ntn_type_notification__type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='u_id',
            new_name='uu_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='u_id',
            new_name='uu_id',
        ),
    ]
